[window]
opacity = 0.7
padding = { x = 10, y = 10 }
decorations = "transparent"


[font]
size = 10

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Thin"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "BoldItalic"
[colors.primary]
background = "#111111"  # or your preferred color
