[window]
opacity = 0.70
padding = { x = 20, y = 20 }
decorations = "none"


[font]
size = 10

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Thin"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "BoldItalic"
[colors.primary]
background = "#111111"  # or your preferred color
